- components/Footer.js
- package-lock.json
- package.json
- pages/_document.js
- pages/charcuterie.js
Resolves #15. Started off the Footer component and added some social media icons to it. Styles might need some tweaking (eg. hover animation, spacing) but figured might as well start it.
I added `styled-components` and configured it for Next.js, which involved a workaround. The new `_document.js` file fixes styles breaking when reloading. I opted to use FontAwesome packages as our icon solution because it's what I'm familiar with, but if anyone has a different opinion I'm happy to hear it out.
> Create footer component and social media icons

- components/Carousel.js
- package.json
- pages/charcuterie.js
Resolves #6. Carousel component. Takes a list of images as the input and the width/height of the carousel. Can scroll through images using arrows. Has diamonds to represent which image is currently shown.
colors aren't right right now
> Carousel implementation

- components/Carousel.js
> remove ternary statement

- .eslintignore
- .eslintrc
- .eslintrc.json
- package-lock.json
- package.json
- pages/_app.js
1. Set up ThemeProvider for the main colors used in the app
- usage example
```
const StyledButton = styled.p`
background: ${p => p.theme.primaryGradient};
// ... rest of styles
```
2. Set up eslint
- to run: `npm run lint`
Regarding 1.
- as we create more components, we may want to extend the current theme definitions in `_app.js`
- for example, when working on typography components, we may want to have specific properties like the `font-style`, `font-weight`, `font-size`, `letter-spacing` for text elements (heading levels, body, etc.)
Closes #20
> Set up ThemeProvider and linting

- .gitignore
- utilities/firebase.js
> Add firebase connection

- components/Footer.js
- components/NavBar.js
- components/Team.js
Couple of fixes:
1. Nav bar wasn't listening to scroll events any more and was not fading. This was because I thought I could remove the parentheses on the function call but turns out you can't :')
2. The text in the footer was the wrong color. It should have be white text that is green on highlight, so I just swapped that around
> Fix navbar, fix footer colors

- components/ResourceFilterCard.js
- components/ResourceFilterTriangle.js
Closes #93 
Resource filters are collapsible/expandable by clicking on the header of each filter card.
> filters are now collapsible

- components/Team.js
- pages/charcuterie.js
changing the team photos to 46 px on the side instead of the 100px on desktop
There is a bunch of linter style fixes going on there, but feel free to focus on changes to the component `ProfileImage`
> adding mobile style

- components/NewsletterModal.js
> fix email closing on valid submission

- components/Hackathons.js
Changing HackCamp registration to be open in hackathons section.
> Open registration for HC2021

- components/Hackathons.js
Update nwHacks card to show registration open instead of closed
> Update nwHacks card to show registration open

- components/Hackathons.js
Close nwHacks 2022 registration on the website.
> Close nwHacks registration

- components/Hackathons.js
- cahnged open key value to false under HackCampData in Hackathons.js
> close hackcamp reg card

- components/Hackathons.js
- nwHacks date: 14-15 -> 21-22, registration open: true-> false
- cmd-f date: March 5-6 -> March 11-12
> updated hackathon cards information

- components/Hackathons.js
- components/Typography.js
Updates the subscribe to newsletter button to make it more prominent.
Desktop:
Mobile:
Some changes are just formatting changes, I have prettier as default code formatter on VSC so maybe this happened because these files weren't formatted with prettier before.
> Update newsletter button

- components/Banner.js
> Change date to Nov 28th

- components/Banner.js
> Update nwHacks banner date to Dec 1 2023

- .github/workflows/firebase-hosting-merge.yml
- .github/workflows/firebase-hosting-pull-request.yml
- fixes CI/CD after breaking firebase-tools change
> Specify firebase-tools version for ci cd

- components/Footer.js
- pages/apply.js
> Copyright year 2023 -> 2024

- components/Footer.js
Updated the titles to make sure they're consistent
> Fix profile titles

- components/ResourceCard.js
- components/ResourceContainer.js
- components/ResourceFilterDropdown.js
- components/ResourcePage.js
- components/Stats.js
- pages/index.js
- utils/ResourceUtils.js
- Added hackathon videos from last year
- Fixed pagination issues
- Got rid of redundant card flip animation on stats
> Add recent hackathon videos + fix resource pagination

- components/Hero.js
> fix the margin on the submit button

- components/Hackathons.js
Ticket: [https://www.notion.so/nwplus/fix-z-index-for-www-planets-14c14d529faa8009b4a9d4b2518c734e]( https://www.notion.so/nwplus/fix-z-index-for-www-planets-14c14d529faa8009b4a9d4b2518c734e)
- add `z-index` to `MoonContainer`
- moved positioning of years a little bit to the right
- made HC 2021 moon higher so it doesn't overlap w cmd-f planet
- made HC 2023 a bit lower
- moved nwHacks 2022 moon a little lower
- formatting changes (unintentionally LOL)
> ui and z-score changes for hackathon moons

- pages/index.js
Completes [https://www.notion.so/nwplus/www-Update-www-nwPlus-Messaging-1e514d529faa808591cfc4ffc8324e09](https://www.notion.so/nwplus/www-Update-www-nwPlus-Messaging-1e514d529faa808591cfc4ffc8324e09)
Before
After
> Update nwPlus messaging

- components/Hero.js
tweaked font for mailing list in hero
> minor tweak mailing list UI
